version: '3'

services:
    airtribe-backend:
        image: airtribe-backend:latest
        restart: always
        build: .
        ports:
            - 3000:3000
        depends_on:
            mysql-airtribe:
                condition: service_healthy

    mysql-airtribe:
        restart: unless-stopped
        container_name: mysql-airtribe
        image: mysql:5.6
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: airtribe
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: root
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 5
